import type {
  User,
  MedicineCategory,
  Medicine,
  MedicineBatch,
  Supplier,
  Purchase,
  Sale,
  Notification,
} from "./types"

// Helper to generate IDs
const generateId = () => Math.random().toString(36).substring(2, 15)

// Users
export const users: User[] = [
  {
    id: "user-1",
    username: "admin",
    email: "admin@pharmacy.com",
    passwordHash: "admin123", // In production, this would be hashed
    role: "Admin",
    fullName: "System Administrator",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    lastLogin: new Date(),
  },
  {
    id: "user-2",
    username: "pharmacist",
    email: "pharmacist@pharmacy.com",
    passwordHash: "pharma123",
    role: "Pharmacist",
    fullName: "John Smith",
    isActive: true,
    createdAt: new Date("2024-01-15"),
    lastLogin: new Date(),
  },
  {
    id: "user-3",
    username: "staff",
    email: "staff@pharmacy.com",
    passwordHash: "staff123",
    role: "Staff",
    fullName: "Jane Doe",
    isActive: true,
    createdAt: new Date("2024-02-01"),
  },
]

// Categories
export const categories: MedicineCategory[] = [
  { id: "cat-1", name: "Antibiotics", description: "Medicines that fight bacterial infections" },
  { id: "cat-2", name: "Pain Relief", description: "Analgesics and pain management medicines" },
  { id: "cat-3", name: "Cardiovascular", description: "Heart and blood vessel medicines" },
  { id: "cat-4", name: "Diabetes", description: "Blood sugar management medicines" },
  { id: "cat-5", name: "Vitamins & Supplements", description: "Nutritional supplements" },
  { id: "cat-6", name: "Respiratory", description: "Medicines for breathing conditions" },
  { id: "cat-7", name: "Gastrointestinal", description: "Digestive system medicines" },
  { id: "cat-8", name: "Dermatology", description: "Skin care medicines" },
]

// Suppliers
export const suppliers: Supplier[] = [
  {
    id: "sup-1",
    name: "PharmaCorp International",
    contactPerson: "Michael Johnson",
    email: "orders@pharmacorp.com",
    phone: "+1-555-0101",
    address: "123 Pharma Street, Medical District, NY 10001",
    isActive: true,
    createdAt: new Date("2023-06-01"),
  },
  {
    id: "sup-2",
    name: "MediSupply Co.",
    contactPerson: "Sarah Williams",
    email: "sales@medisupply.com",
    phone: "+1-555-0102",
    address: "456 Health Avenue, Boston, MA 02101",
    isActive: true,
    createdAt: new Date("2023-07-15"),
  },
  {
    id: "sup-3",
    name: "Global Meds Distribution",
    contactPerson: "Robert Chen",
    email: "contact@globalmeds.com",
    phone: "+1-555-0103",
    address: "789 Medicine Road, Chicago, IL 60601",
    isActive: true,
    createdAt: new Date("2023-08-20"),
  },
]

// Medicines
export const medicines: Medicine[] = [
  {
    id: "med-1",
    name: "Amoxicillin 500mg",
    genericName: "Amoxicillin",
    categoryId: "cat-1",
    manufacturer: "PharmaCorp",
    dosageForm: "Capsule",
    strength: "500mg",
    unitPrice: 0.50,
    reorderLevel: 100,
    description: "Broad-spectrum antibiotic",
    requiresPrescription: true,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "med-2",
    name: "Ibuprofen 400mg",
    genericName: "Ibuprofen",
    categoryId: "cat-2",
    manufacturer: "MediSupply",
    dosageForm: "Tablet",
    strength: "400mg",
    unitPrice: 0.25,
    reorderLevel: 200,
    description: "Non-steroidal anti-inflammatory drug",
    requiresPrescription: false,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "med-3",
    name: "Metformin 850mg",
    genericName: "Metformin",
    categoryId: "cat-4",
    manufacturer: "Global Meds",
    dosageForm: "Tablet",
    strength: "850mg",
    unitPrice: 0.35,
    reorderLevel: 150,
    description: "Oral diabetes medicine",
    requiresPrescription: true,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "med-4",
    name: "Lisinopril 10mg",
    genericName: "Lisinopril",
    categoryId: "cat-3",
    manufacturer: "PharmaCorp",
    dosageForm: "Tablet",
    strength: "10mg",
    unitPrice: 0.45,
    reorderLevel: 100,
    description: "ACE inhibitor for blood pressure",
    requiresPrescription: true,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "med-5",
    name: "Vitamin D3 1000IU",
    genericName: "Cholecalciferol",
    categoryId: "cat-5",
    manufacturer: "HealthPlus",
    dosageForm: "Softgel",
    strength: "1000IU",
    unitPrice: 0.15,
    reorderLevel: 300,
    description: "Vitamin D supplement",
    requiresPrescription: false,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "med-6",
    name: "Omeprazole 20mg",
    genericName: "Omeprazole",
    categoryId: "cat-7",
    manufacturer: "MediSupply",
    dosageForm: "Capsule",
    strength: "20mg",
    unitPrice: 0.55,
    reorderLevel: 120,
    description: "Proton pump inhibitor for acid reflux",
    requiresPrescription: true,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "med-7",
    name: "Cetirizine 10mg",
    genericName: "Cetirizine",
    categoryId: "cat-6",
    manufacturer: "Global Meds",
    dosageForm: "Tablet",
    strength: "10mg",
    unitPrice: 0.20,
    reorderLevel: 250,
    description: "Antihistamine for allergies",
    requiresPrescription: false,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "med-8",
    name: "Hydrocortisone Cream 1%",
    genericName: "Hydrocortisone",
    categoryId: "cat-8",
    manufacturer: "DermaCare",
    dosageForm: "Cream",
    strength: "1%",
    unitPrice: 4.50,
    reorderLevel: 50,
    description: "Topical corticosteroid for skin conditions",
    requiresPrescription: false,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

// Medicine Batches
export const batches: MedicineBatch[] = [
  {
    id: "batch-1",
    medicineId: "med-1",
    batchNumber: "AMX-2024-001",
    quantity: 500,
    manufacturingDate: new Date("2024-01-15"),
    expiryDate: new Date("2026-01-15"),
    purchasePrice: 0.30,
    sellingPrice: 0.50,
    supplierId: "sup-1",
    receivedDate: new Date("2024-02-01"),
  },
  {
    id: "batch-2",
    medicineId: "med-2",
    batchNumber: "IBU-2024-001",
    quantity: 1000,
    manufacturingDate: new Date("2024-02-01"),
    expiryDate: new Date("2026-02-01"),
    purchasePrice: 0.15,
    sellingPrice: 0.25,
    supplierId: "sup-2",
    receivedDate: new Date("2024-02-15"),
  },
  {
    id: "batch-3",
    medicineId: "med-3",
    batchNumber: "MET-2024-001",
    quantity: 75, // Low stock
    manufacturingDate: new Date("2024-01-20"),
    expiryDate: new Date("2025-03-20"), // Expiring soon
    purchasePrice: 0.20,
    sellingPrice: 0.35,
    supplierId: "sup-3",
    receivedDate: new Date("2024-02-10"),
  },
  {
    id: "batch-4",
    medicineId: "med-4",
    batchNumber: "LIS-2024-001",
    quantity: 300,
    manufacturingDate: new Date("2024-03-01"),
    expiryDate: new Date("2026-03-01"),
    purchasePrice: 0.25,
    sellingPrice: 0.45,
    supplierId: "sup-1",
    receivedDate: new Date("2024-03-15"),
  },
  {
    id: "batch-5",
    medicineId: "med-5",
    batchNumber: "VIT-2024-001",
    quantity: 800,
    manufacturingDate: new Date("2024-02-15"),
    expiryDate: new Date("2026-02-15"),
    purchasePrice: 0.08,
    sellingPrice: 0.15,
    supplierId: "sup-2",
    receivedDate: new Date("2024-03-01"),
  },
  {
    id: "batch-6",
    medicineId: "med-6",
    batchNumber: "OME-2024-001",
    quantity: 45, // Low stock
    manufacturingDate: new Date("2024-01-10"),
    expiryDate: new Date("2025-02-10"), // Expiring very soon
    purchasePrice: 0.35,
    sellingPrice: 0.55,
    supplierId: "sup-3",
    receivedDate: new Date("2024-01-25"),
  },
  {
    id: "batch-7",
    medicineId: "med-7",
    batchNumber: "CET-2024-001",
    quantity: 600,
    manufacturingDate: new Date("2024-03-10"),
    expiryDate: new Date("2026-03-10"),
    purchasePrice: 0.12,
    sellingPrice: 0.20,
    supplierId: "sup-1",
    receivedDate: new Date("2024-03-25"),
  },
  {
    id: "batch-8",
    medicineId: "med-8",
    batchNumber: "HYD-2024-001",
    quantity: 120,
    manufacturingDate: new Date("2024-02-20"),
    expiryDate: new Date("2026-02-20"),
    purchasePrice: 2.50,
    sellingPrice: 4.50,
    supplierId: "sup-2",
    receivedDate: new Date("2024-03-05"),
  },
]

// Purchases
export const purchases: Purchase[] = [
  {
    id: "pur-1",
    supplierId: "sup-1",
    purchaseDate: new Date("2024-02-01"),
    totalAmount: 650.00,
    status: "Received",
    items: [
      {
        id: "pi-1",
        purchaseId: "pur-1",
        medicineId: "med-1",
        quantity: 500,
        unitPrice: 0.30,
        batchNumber: "AMX-2024-001",
        expiryDate: new Date("2026-01-15"),
      },
      {
        id: "pi-2",
        purchaseId: "pur-1",
        medicineId: "med-4",
        quantity: 500,
        unitPrice: 1.00,
        batchNumber: "LIS-2024-001",
        expiryDate: new Date("2026-03-01"),
      },
    ],
    createdBy: "user-1",
    notes: "Regular monthly stock replenishment",
  },
  {
    id: "pur-2",
    supplierId: "sup-2",
    purchaseDate: new Date("2024-02-15"),
    totalAmount: 350.00,
    status: "Received",
    items: [
      {
        id: "pi-3",
        purchaseId: "pur-2",
        medicineId: "med-2",
        quantity: 1000,
        unitPrice: 0.15,
        batchNumber: "IBU-2024-001",
        expiryDate: new Date("2026-02-01"),
      },
      {
        id: "pi-4",
        purchaseId: "pur-2",
        medicineId: "med-5",
        quantity: 1000,
        unitPrice: 0.20,
        batchNumber: "VIT-2024-001",
        expiryDate: new Date("2026-02-15"),
      },
    ],
    createdBy: "user-1",
  },
  {
    id: "pur-3",
    supplierId: "sup-3",
    purchaseDate: new Date("2024-03-01"),
    totalAmount: 275.00,
    status: "Pending",
    items: [
      {
        id: "pi-5",
        purchaseId: "pur-3",
        medicineId: "med-3",
        quantity: 500,
        unitPrice: 0.20,
        batchNumber: "MET-2024-002",
        expiryDate: new Date("2026-06-01"),
      },
      {
        id: "pi-6",
        purchaseId: "pur-3",
        medicineId: "med-6",
        quantity: 500,
        unitPrice: 0.35,
        batchNumber: "OME-2024-002",
        expiryDate: new Date("2026-06-15"),
      },
    ],
    createdBy: "user-2",
    notes: "Urgent reorder for low stock items",
  },
]

// Sales
export const sales: Sale[] = [
  {
    id: "sale-1",
    invoiceNumber: "INV-2024-0001",
    saleDate: new Date(),
    customerName: "John Doe",
    totalAmount: 25.00,
    discount: 0,
    tax: 2.00,
    netAmount: 27.00,
    paymentMethod: "Cash",
    status: "Completed",
    items: [
      {
        id: "si-1",
        saleId: "sale-1",
        medicineId: "med-2",
        batchId: "batch-2",
        quantity: 20,
        unitPrice: 0.25,
        discount: 0,
        totalPrice: 5.00,
      },
      {
        id: "si-2",
        saleId: "sale-1",
        medicineId: "med-5",
        batchId: "batch-5",
        quantity: 30,
        unitPrice: 0.15,
        discount: 0,
        totalPrice: 4.50,
      },
      {
        id: "si-3",
        saleId: "sale-1",
        medicineId: "med-1",
        batchId: "batch-1",
        quantity: 14,
        unitPrice: 0.50,
        discount: 0,
        totalPrice: 7.00,
      },
    ],
    soldBy: "user-2",
  },
  {
    id: "sale-2",
    invoiceNumber: "INV-2024-0002",
    saleDate: new Date(),
    customerName: "Jane Smith",
    totalAmount: 45.50,
    discount: 5.00,
    tax: 3.24,
    netAmount: 43.74,
    paymentMethod: "Card",
    status: "Completed",
    items: [
      {
        id: "si-4",
        saleId: "sale-2",
        medicineId: "med-3",
        batchId: "batch-3",
        quantity: 30,
        unitPrice: 0.35,
        discount: 0,
        totalPrice: 10.50,
      },
      {
        id: "si-5",
        saleId: "sale-2",
        medicineId: "med-4",
        batchId: "batch-4",
        quantity: 30,
        unitPrice: 0.45,
        discount: 0,
        totalPrice: 13.50,
      },
      {
        id: "si-6",
        saleId: "sale-2",
        medicineId: "med-6",
        batchId: "batch-6",
        quantity: 20,
        unitPrice: 0.55,
        discount: 0,
        totalPrice: 11.00,
      },
    ],
    soldBy: "user-2",
    notes: "Regular customer - 5% discount applied",
  },
  {
    id: "sale-3",
    invoiceNumber: "INV-2024-0003",
    saleDate: new Date(Date.now() - 86400000), // Yesterday
    customerName: "Bob Wilson",
    totalAmount: 18.00,
    discount: 0,
    tax: 1.44,
    netAmount: 19.44,
    paymentMethod: "Mobile",
    status: "Completed",
    items: [
      {
        id: "si-7",
        saleId: "sale-3",
        medicineId: "med-7",
        batchId: "batch-7",
        quantity: 30,
        unitPrice: 0.20,
        discount: 0,
        totalPrice: 6.00,
      },
      {
        id: "si-8",
        saleId: "sale-3",
        medicineId: "med-8",
        batchId: "batch-8",
        quantity: 2,
        unitPrice: 4.50,
        discount: 0,
        totalPrice: 9.00,
      },
    ],
    soldBy: "user-3",
  },
]

// Notifications
export const notifications: Notification[] = [
  {
    id: "notif-1",
    type: "LowStock",
    title: "Low Stock Alert",
    message: "Metformin 850mg is running low (75 units remaining)",
    isRead: false,
    createdAt: new Date(),
    relatedEntityId: "med-3",
    relatedEntityType: "Medicine",
  },
  {
    id: "notif-2",
    type: "LowStock",
    title: "Low Stock Alert",
    message: "Omeprazole 20mg is running low (45 units remaining)",
    isRead: false,
    createdAt: new Date(),
    relatedEntityId: "med-6",
    relatedEntityType: "Medicine",
  },
  {
    id: "notif-3",
    type: "Expiring",
    title: "Expiry Warning",
    message: "Batch OME-2024-001 of Omeprazole 20mg expires on Feb 10, 2025",
    isRead: false,
    createdAt: new Date(),
    relatedEntityId: "batch-6",
    relatedEntityType: "Batch",
  },
  {
    id: "notif-4",
    type: "Expiring",
    title: "Expiry Warning",
    message: "Batch MET-2024-001 of Metformin 850mg expires on Mar 20, 2025",
    isRead: true,
    createdAt: new Date(Date.now() - 86400000),
    relatedEntityId: "batch-3",
    relatedEntityType: "Batch",
  },
  {
    id: "notif-5",
    type: "System",
    title: "System Update",
    message: "System maintenance scheduled for next Sunday at 2:00 AM",
    isRead: true,
    createdAt: new Date(Date.now() - 172800000),
  },
]

// Helper functions to get data with relationships
export function getMedicineWithCategory(medicine: Medicine): Medicine & { category: MedicineCategory | undefined } {
  return {
    ...medicine,
    category: categories.find((c) => c.id === medicine.categoryId),
  }
}

export function getBatchWithRelations(batch: MedicineBatch) {
  return {
    ...batch,
    medicine: medicines.find((m) => m.id === batch.medicineId),
    supplier: suppliers.find((s) => s.id === batch.supplierId),
  }
}

export function getTotalStock(medicineId: string): number {
  return batches
    .filter((b) => b.medicineId === medicineId)
    .reduce((sum, b) => sum + b.quantity, 0)
}

export function generateInvoiceNumber(): string {
  const year = new Date().getFullYear()
  const count = sales.length + 1
  return `INV-${year}-${count.toString().padStart(4, "0")}`
}
